services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/default.conf:ro
      - ./.output/public:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=bdp.blue,www.bdp.blue
      - VIRTUAL_PORTS=80
    restart: unless-stopped
    expose:
      - 80
    networks:
      - frontend
    command: [nginx-debug, '-g', 'daemon off;']


  node-builder:
    image: node:lts-slim
    volumes:
      - ./:./

    command: >
        npm install && nuxt generate




networks:
  frontend:
    name: forward-network
    external: true



