services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.output/public/:/usr/share/nginx/html/:ro
    environment:
      - VIRTUAL_HOST=bdp.blue,www.bdp.blue
      - VIRTUAL_PORTS=80
    restart: unless-stopped
    ports:
      - 80
    networks:
      - frontend
    command: [nginx-debug, '-g', 'daemon off;']


  node-builder:
    image: node:lts-slim
    volumes:
      - .:/app
    working_dir: /app
    command: >
        sh -c "npm install && npm run generate"




networks:
  frontend:
    name: forward-network
    external: true



