name: Build and Push Nuxt App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Build Nuxt App
        run: npm run generate

      - name: Commit and Push to Another Branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b build-output
          git add -f .output/
          git commit -m "Auto-build Nuxt app"
          git push origin build-output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
